# Generated by Django 3.0.4 on 2020-04-13 05:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=6)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date(2020, 4, 13))),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district_info.DistrictInfo')),
            ],
        ),
    ]
