# Generated by Django 3.0.4 on 2020-04-13 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 4, 13))),
                ('new_case', models.PositiveIntegerField()),
                ('new_death', models.PositiveIntegerField()),
                ('new_recovery', models.PositiveIntegerField()),
            ],
        ),
    ]
