# Generated by Django 3.0.4 on 2020-04-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_info', '0002_totalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfo',
            name='cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalinfo',
            name='new_case',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalinfo',
            name='new_death',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalinfo',
            name='new_recovery',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
