# Generated by Django 3.0.4 on 2020-04-15 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_info', '0004_auto_20200414_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfo',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 15)),
        ),
        migrations.AlterField(
            model_name='districtinfo',
            name='dist_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='totalinfo',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 15)),
        ),
    ]
