# Generated by Django 3.0.4 on 2020-04-15 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_info', '0007_auto_20200415_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhitcounter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 23, 57, 20, 532040)),
        ),
    ]
