# Generated by Django 3.0.4 on 2020-04-15 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_info', '0009_auto_20200416_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisioninfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 0, 52, 34, 700285)),
        ),
        migrations.AlterField(
            model_name='webhitcounter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 0, 52, 34, 700844)),
        ),
    ]
