# Generated by Django 3.0.4 on 2020-04-15 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_info', '0011_auto_20200416_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='divisioninfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 0, 58, 41, 583387)),
        ),
        migrations.AlterField(
            model_name='webhitcounter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 0, 58, 41, 584365)),
        ),
        migrations.AlterField(
            model_name='divisioninfo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district_info.DivisionName'),
        ),
    ]
